<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.wx</groupId>
  <artifactId>gymnasium-parent-project</artifactId>
  <version>1.0-SNAPSHOT</version>
  <packaging>pom</packaging>
  <name>Archetype - gymnasium-parent-project</name>
  <url>http://maven.apache.org</url>
  <modules>
    <module>gymnasium-common</module>
    <module>gymnasium-service-web</module>
    <module>gymnasium-service-member</module>
    <module>gymnasium-service-goods</module>
    <module>gymnasium-service-course</module>
    <module>gymnasium-service-user</module>
    <module>gymnasium-service-role</module>
    <module>gymnasium-service-menu</module>
    <module>gymnasium-service-suggest</module>
  </modules>

  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>2.4.4</version>
    <relativePath></relativePath>
  </parent>

  <properties>
    <java.version>1.8</java.version>
    <maven-compiler-plugin.version>3.11.0</maven-compiler-plugin.version>
    <maven-clean-plugin.version>3.3.2</maven-clean-plugin.version>
    <!-- <swagger2.version>3.0.0</swagger2.version>-->
    <lombok-version>1.18.12</lombok-version>
    <mybatis-plus.version>3.4.1</mybatis-plus.version>
    <druid.version>1.2.1</druid.version>
    <kaptcha.version>2.3.2</kaptcha.version>
    <fastjson.version>1.2.69</fastjson.version>
    <commons-lang.version>2.6</commons-lang.version>
    <commons-collections.version>3.2.2</commons-collections.version>
    <commons-io.version>2.6</commons-io.version>
    <mysql-connection.version>8.0.23</mysql-connection.version>
    <jwt.version>3.10.3</jwt.version>
    <easypoi.version>4.2.0</easypoi.version>
    <jwt.version>3.10.3</jwt.version>
    <dubbo.version>2.7.15</dubbo.version>
    <nacos.version>1.4.4</nacos.version>
  </properties>

  <dependencyManagement>
    <dependencies>
      <!-- lombok依赖 -->
      <dependency>
        <groupId>org.projectlombok</groupId>
        <artifactId>lombok</artifactId>
        <version>${lombok-version}</version>
        <scope>provided</scope>
      </dependency>

      <dependency>
        <groupId>mysql</groupId>
        <artifactId>mysql-connector-java</artifactId>
        <version>${mysql-connection.version}</version>
        <scope>runtime</scope>
      </dependency>

      <!--druid连接池-->
      <dependency>
        <groupId>com.alibaba</groupId>
        <artifactId>druid-spring-boot-starter</artifactId>
        <version>${druid.version}</version>
      </dependency>
      <!--mybatis-plus依赖-->
      <dependency>
        <groupId>com.baomidou</groupId>
        <artifactId>mybatis-plus-boot-starter</artifactId>
        <version>${mybatis-plus.version}</version>
      </dependency>
      <!-- kaptcha 图形验证码 -->
      <dependency>
        <groupId>com.github.penggle</groupId>
        <artifactId>kaptcha</artifactId>
        <version>${kaptcha.version}</version>
      </dependency>

      <!-- JSON转换工具类依赖 -->
      <dependency>
        <groupId>com.alibaba</groupId>
        <artifactId>fastjson</artifactId>
        <version>${fastjson.version}</version>
      </dependency>

      <dependency>
        <groupId>commons-lang</groupId>
        <artifactId>commons-lang</artifactId>
        <version>${commons-lang.version}</version>
      </dependency>

      <dependency>
        <groupId>commons-collections</groupId>
        <artifactId>commons-collections</artifactId>
        <version>${commons-collections.version}</version>
      </dependency>

      <dependency>
        <groupId>commons-io</groupId>
        <artifactId>commons-io</artifactId>
        <version>${commons-io.version}</version>
      </dependency>

      <dependency>
        <groupId>com.auth0</groupId>
        <artifactId>java-jwt</artifactId>
        <version>${jwt.version}</version>
      </dependency>

      <dependency>
        <groupId>cn.afterturn</groupId>
        <artifactId>easypoi-spring-boot-starter</artifactId>
        <version>${easypoi.version}</version>
      </dependency>

      <dependency>
        <groupId>org.apache.dubbo</groupId>
        <artifactId>dubbo-spring-boot-starter</artifactId>
        <version>${dubbo.version}</version>
      </dependency>

      <dependency>
        <groupId>org.apache.dubbo</groupId>
        <artifactId>dubbo-registry-nacos</artifactId>
        <version>${dubbo.version}</version>
      </dependency>

      <dependency>
        <groupId>com.alibaba.nacos</groupId>
        <artifactId>nacos-client</artifactId>
        <version>${nacos.version}</version>
      </dependency>

    </dependencies>
  </dependencyManagement>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>${maven-compiler-plugin.version}</version>
        <configuration>
          <source>${java.version}</source>
          <target>${java.version}</target>
          <useIncrementalCompilation>false</useIncrementalCompilation>
        </configuration>
      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-clean-plugin</artifactId>
        <version>${maven-clean-plugin.version}</version>
        <executions>
          <execution>
            <id>purge-output-dirs-before-build</id>
            <phase>initialize</phase>
            <goals>
              <goal>clean</goal>
            </goals>
            <configuration>
              <excludeDefaultDirectories>true</excludeDefaultDirectories>
              <filesets>
                <fileset>
                  <directory>${project.build.outputDirectory}</directory>
                </fileset>
                <fileset>
                  <directory>${project.build.testOutputDirectory}</directory>
                </fileset>
              </filesets>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
