# 设置日志级别为 INFO，输出到控制台
log4j.rootLogger=INFO, Console

# 控制台输出配置
log4j.appender.Console=org.apache.log4j.ConsoleAppender
log4j.appender.Console.layout=org.apache.log4j.PatternLayout
log4j.appender.Console.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} [%t] %-5p %c - %m%n

# 屏蔽 Dubbo 内部过多的调试信息
log4j.logger.org.apache.dubbo=WARN